redhat-openshift-ecosystem/provider-certification-plugins

openshift-provider-cert, tools/openshift-provider-cert-plugin/executor.sh, tools/openshift-provider-cert-plugin/global_fn.sh, tools/openshift-provider-cert-plugin/runner.sh
Check `openshift-tests` utility after extractor. It will fail fast when is unable to download from image-registry.
The image registry is required for the environment work, and it is mapped to be checked on the CLI (the `run` will not run if there's no registry deployed on the cluster[1])
Related to:
- https://issues.redhat.com/browse/SPLAT-598
References:
- [1] https://issues.redhat.com/browse/SPLAT-603
Blocked by:
=> fix(plugin-cert): test, and fail fast if need, openshift-tests on extractor

tools/openshift-provider-cert-plugin/executor.sh, tools/openshift-provider-cert-plugin/global_env.sh, tools/openshift-provider-cert-plugin/global_fn.sh, tools/openshift-provider-cert-plugin/runner.sh
That change comes from discussions and research about modifying openshift-tests[1].
We can see we modify the parallelism we can take more control of the total resources allocated to the environment, on the other hand, it will impact the total execution time.
This PR will allow changing this value externally, but not implementing anything on CLI or setting on the manifest as we need to understand the good value, or if needs to be set when running in the non-dedicated environment[2].
[1] https://coreos.slack.com/archives/C02DSMAP4LA/p1654727293626179?thread_ts=1654262916.956689&cid=C02DSMAP4LA
[2] https://issues.redhat.com/browse/SPLAT-622
```
$ ./openshift-tests run --help
--max-parallel-tests int   Maximum number of tests running in parallel. 0 defaults to test suite recommended value, …
```
=> feat(plugin-cert): exposing E2E_PARALLEL var to be used externally

openshift-tests-provider-cert/plugin/executor.sh, openshift-tests-provider-cert/plugin/global_env.sh, openshift-tests-provider-cert/plugin/global_fn.sh, openshift-tests-provider-cert/plugin/report-progress.sh
Fix blocker https://issues.redhat.com/browse/SPLAT-627
Using shared volume to store `openshift-tests` utility and avoid extracting on each container. The extractor will be on the plugin container, and the dependencies will be blocked waiting for it (normal flow).
=> fix(plugin-cert): extractor run once and share the openshift-tests

openshift-tests-provider-cert/plugin/global_env.sh, openshift-tests-provider-cert/plugin/global_fn.sh, openshift-tests-provider-cert/plugin/report-progress.sh, openshift-tests-provider-cert/plugin/runner.sh
Improve container signal file handlers:
- fix: adding `plugin.done` signal to `report-progress` container correctly know when the plugin has finished, regardless of any post-processor workflow (that removes the default `done` file).
- feat: creates the extractor failed signal, to correctly exit when the extractor has failed.
=> fix(provider-cert): imrprove file handler signals to inter container communication

openshift-tests-provider-cert/plugin/executor.sh
The files exist but the log is reporting as not due to the wrong test evaluation
```
#./executor.sh:17>  [executor] secret not found=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#./executor.sh:18>  [executor] secret not found=/var/run/secrets/kubernetes.io/serviceaccount/token
```
=> SPLAT-871 - fix(plugin-log): the should test exists checking the error

openshift-tests-provider-cert/hack/build-image.sh
https://issues.redhat.com/browse/SPLAT-870
Update the Tools image for those reasons:
- update OC client to 4.11
- sync sonobuoy version with CLI: https://github.com/redhat-openshift-ecosystem/provider-certification-tool/blob/main/go.mod#L13
- security updates from Alpine
=> SPLAT-870 - bump/tools: update tools image to sync for security and sync with CLI

openshift-tests-provider-cert/plugin/executor.sh, openshift-tests-provider-cert/plugin/global_env.sh, openshift-tests-provider-cert/plugin/global_fn.sh, openshift-tests-provider-cert/plugin/wait-plugin.sh
Rename the plugin to reflect the order of execution.
https://issues.redhat.com/browse/SPLAT-869
Relates to: 
- https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/30
- https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/31
=> SPLAT-869 - chore/manifests: rename plugins to be ordered by execution

openshift-tests-provider-cert/plugin/global_fn.sh
Fix check introduced on https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/26
This PR blocks https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/23
https://issues.redhat.com/browse/SPLAT-881
=> SPLAT-881 - fix: check deprecated env var CERT_LEVEL

openshift-tests-provider-cert/hack/Containerfile.alp, openshift-tests-provider-cert/hack/build-image.sh, openshift-tests-provider-cert/plugin/executor.sh, openshift-tests-provider-cert/plugin/global_env.sh, openshift-tests-provider-cert/plugin/global_fn.sh
This PR is a result of a regression investigation described on SPLAT-909 when validating the release v0.2.0 compared with the results of v0.1.0. The failures ratio increased from less than 1% to ~2.5% on OpenShift Conformance results running in cluster 4.10.z, which is not desired as the certification environment should not impact the test results
The root cause is on [this PR](https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/22) we bump the versions from the base image, which includes the update of oc (OpenShift CLI) from 4.10.18 to 4.11.13 used by `openshift-tests` utility.
That upgrade, ideally, should not impact. But we understood that the `openshift-tests` utility is validated, tested, and shipped in the payload, including the CLI for the same …
=> fix/splat-909: extracting oc from tests image - fix regressions

openshift-tests-provider-cert/plugin/global_env.sh, openshift-tests-provider-cert/plugin/report-progress.sh, openshift-tests-provider-cert/plugin/wait-plugin.sh
Changes related to card OPCT-15.
This change increases the timeout of the blocker plugin to prevent the plugins start early when the blocker is taking longer (for example upgrade plugin used to take more than the current default).
Another plugin that can't start early is the artifacts collector, it could happen when the OCP conformance tests got stuck.
This change was initially implemented and tested on upgrade feature #24.
=> OPCT-15 - fix/waiter: increase plugin blocker timeout

openshift-tests-provider-cert/plugin/global_env.sh, openshift-tests-provider-cert/plugin/report-progress.sh, openshift-tests-provider-cert/plugin/wait-plugin.sh
This PR prevents the blocker plugin to wait longer (until timeout) to run when the blocker plugin has been failed.
https://issues.redhat.com/browse/OPCT-23
=> OPCT-23 - fix/waiter: unblock waiter when previous job failed

openshift-tests-provider-cert/plugin/executor.sh, openshift-tests-provider-cert/plugin/report-progress.sh
Refact to:
- split the executor into chunks, and remove old fragments not valid for the current plugin (custom file, custom E2E, etc)
- standardized the files collected by the collector plugin, and processed by CLI[1]
[1] https://issues.redhat.com/browse/OPCT-9
Blocked by
=> OPCT-9: Refact executor to run chunks by plugin

openshift-tests-provider-cert/hack/build-image.sh
https://issues.redhat.com/browse/OPCT-179
Changes:
1) Fixing the CVE-2022-43551 impacting `libcurl `and `curl` on the base image: https://quay.io/repository/ocp-cert/openshift-tests-provider-cert/manifest/sha256:7da47f5b75fce38b70f5cf09cc2fbe39264abbdeb111af7f31d2ae6f0b2fb183?tab=vulnerabilities
2) bump the OC cli to the current GA (4.12)
Steps to publish:
1) make the changes on the base image
2) build and push it (there is no pipeline for the plugin image)
```
$ bash hack/build-image.sh build-tools
$ bash hack/build-image.sh push-tools
```
3) Build the plugin image
- Review if the plugin image can be build with new base image
```
$ make build-dev
```
- Test the plugin image
=> OPCT-179: Bump base image to fix CVE; Update OC

.github/workflows/changelog-configuration.json, .github/workflows/ci.yaml
https://issues.redhat.com/browse/OPCT-192
This PR introduces the action plugin to generate the changelog for each release.
=> OPCT-192: Automatically create changelog based on the tags

openshift-tests-provider-cert/.gitignore, openshift-tests-provider-cert/Makefile, openshift-tests-provider-cert/cmd/ocp-etcd-log-filters/applyTookLong.go, openshift-tests-provider-cert/cmd/ocp-etcd-log-filters/buckets.go, openshift-tests-provider-cert/cmd/ocp-etcd-log-filters/main.go, openshift-tests-provider-cert/hack/Containerfile.tools-alp, openshift-tests-provider-cert/hack/build-image.sh, openshift-tests-provider-cert/plugin/executor.sh
https://issues.redhat.com/browse/OPCT-12
Embed the tool used on the review process to parse etcd logs from must-gather filtering by slowly apply requests. It will aggregate the slow requests into buckets of 100ms, sharing counters for each one and which bucket the slow requests stayed, useful when comparing executions with baseline HW (reference) and new ones on the time frame the e2e tests have.
For reference:
- expected to have fewer requests reporting higher than 500ms
```
$ cat ~/opct/tmp/must-gather/must-gather-opct/*/namespaces/openshift-etcd/pods/*/etcd/etcd/logs/current.log  \
| ./build/ocp-etcd-log-filters 
> Filter Name: ApplyTookTooLong
> Group by: all
>>> Summary <<<
all	 16949	
>500ms	 1485	(8.762 %)
---
>>> Buckets <<<
low-200	 0	(0.000 %)
200-300	 9340	(55.106 %)
300-400 …
```
=> OPCT-12: Embed on tools image the etcd log parser

openshift-tests-provider-cert/hack/Containerfile.tools-alp, openshift-tests-provider-cert/hack/build-image.sh
Fixes:
- Replace plugin image to UBI, resolving bugs related of Go 1.20 (OCP 4.14) binaries (glibc dependencies) and Alpine (details in https://issues.redhat.com/browse/OPCT-213 ) [1]
- JQ new URL path
- Moving tag name to SemVer (intro with v0.1.0)
Updates:
- oc client to 4.13-based
[1] Plugin error when running Go binaries built with Go 1.20 in OCP 4.14
~~~
2023-06-13_23:57:12 | [plugin] | ./global_fn.sh:231>  [extractor_start][openshift-tests] testing openshift-tests
Error loading shared library libresolv.so.2: No such file or directory (needed by /tmp/shared/openshift-tests)
2023-06-13_23:57:12 | [plugin] | ./global_fn.sh:180>  Creating failed JUnit result file [/tmp/sonobuoy/results/junit_e2e_failed_20230613-235712.xml]
~~~
blocks …
=> OPCT-213: Update base image for plugin provider-cert (v0.1.0)

openshift-tests-provider-cert/hack/Containerfile.tools-alp, openshift-tests-provider-cert/hack/build-image.sh, openshift-tests-provider-cert/plugin/executor.sh
This change introduces the [camgi](https://github.com/elmiko/camgi.rs) report to the artifact collector plugin - results artifacts:
~~~
$ tree plugins/99-openshift-artifacts-collector/
plugins/99-openshift-artifacts-collector/
├── definition.json
├── results
│   └── global
(...)
│       ├── artifacts_must-gather_camgi.html
(...)
└── sonobuoy_results.yaml
~~~
CAMGI is a tool broadly used in OCP CI to help to troubleshoot many objects in must-gather with a friendly interface.
The binary is pretty small, increasing 700 MiB to the compressed image in the Quay.io, and ~1MiB local.
~~~
$ podman images |grep tools
quay.io/ocp-cert/tools                                   v0.1.0                              66dad94e6c9f  56 minutes ago  253 MB
quay.io/ocp-cert/tools …
=> OPCT-226: Added camgi report to artifact collector plugin

must-gather-monitoring/Containerfile, must-gather-monitoring/Makefile, must-gather-monitoring/README.md, must-gather-monitoring/collection-scripts/gather, must-gather-monitoring/plugin.yaml, must-gather-monitoring/runner_plugin, openshift-tests-provider-cert/plugin/executor.sh, openshift-tests-provider-cert/plugin/global_env.sh, openshift-tests-provider-cert/plugin/global_fn.sh, openshift-tests-provider-cert/plugin/wait-plugin.sh
Introduce a must-gather-like collector to extract metrics from Prometheus.
The image for the custom must-gather (must-gather-monitoring) will be triggered by the artifact collector plugin, compacting all the metrics into a single compressed tarball file.
The metrics collected by default are extracted from the main widgets in the OCP Dashboards, prioritizing elaborated expressions to save storage in client side, and CPU and Memory in the server side.
The total of storage incremented in the final tarball file are less than 1MiB in the samples collected. o/
There are no tool to read and process the raw metrics yet, but it can be consumed in the future by the OPCT report or use opensource projects to load/back fill prometheus db to read it in the monitoring-like tools (anyone that requires …
=> OPCT-246: Introducing must-gather-monitoring to collect metrics

openshift-tests-provider-cert/hack/Containerfile.tools-alp, openshift-tests-provider-cert/hack/build-image.sh
Backport #43 on v0.4 to support OCP 4.14.
The intention is to create v0.4.1 while v0.5 is not yet release as there are folks using OPCT in OCP 4.14 outside of the development.
=> OPCT-213: Backport #43 | update base image for 4.14

openshift-tests-provider-cert/plugin/executor.sh
Supporting disconnected for new collectors.
- must-gather-monitoring added in https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/45
-  etcdfio added in https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/46
- Don't break for any collectors
- CLI change is added in the PR https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/83
=> OPCT-242: support to use mirror images of items added in v0.5

.github/workflows/ci.yaml, .github/workflows/release-devel.yaml
- Isolate tag release jobs to a dedicated workflow trigered by push on
tags prefixed with 'v*'
- Isolate devel container image release added on https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/51
=> OPCT-257: fixes ci workflow preventing release deployment

.github/workflows/ci.yaml
> This is a backport patching and fixing the release pipeline applied on branch `release-v0.5` (#59). It should be merged to `main` to feed the #57
CI pipeline is crashing when publishing a tag using an old build method.
This syncronizes to main the fixes applied in `release-0.5` branch (and tag [v0.5.0-alpha.4](https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/releases/tag/v0.5.0-alpha.4)):
- missing dependencies from #51 by calling the new multi-arch build scripts.
- unsupported step for docker login in Pull Requests from forks (external pushes)
- fix push expiration for PR builds on local branches.
=> OPCT-257: fixes/ci pipeline to publish multi-arch manifests (#59)

must-gather-monitoring/Containerfile, must-gather-monitoring/collection-scripts/gather
Problem: metrics is not correctly collected during artifacts collector with must-gather-metrics exporter.
Reason: URI is not correctly encoded when constructing the URL query to Prometheus, then the request is rejected by server.
Steps to reproduce:
- run standalone metrics collector: `oc adm must-gather --image=quay.io/opct/must-gather-monitoring:v0.5.0`
- check the errors in: `must-gather.local.*/*/monitoring/prometheus/metrics/*.stderr`
=> OPCT-298: mmg: Fix URI encoder when creating query URL

openshift-tests-plugin/pkg/plugin/plugin.go, openshift-tests-plugin/plugin/entrypoint-tests.sh
Following up changes:
https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/117
https://issues.redhat.com/browse/OPCT-300
=> OPCT-300: chaning Kube service URL

openshift-tests-plugin/plugin/platform.sh
Changes add the setup_provider_gce function as discussed offline with mrbraga.
=> NO-JIRA: Enable configuration for platform type GCP for test framework

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/PULL_REQUEST_TEMPLATE.md
Completing the Community Standards: https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/community
https://issues.redhat.com/browse/OPCT-336
https://issues.redhat.com/browse/OPCT-239
=> OPCT-336: added github templates for issues and PR

artifacts-collector/collector.sh
**What this PR does / why we need it**:
With the e2e controller, the logs is something nice to have to troubleshoot e2e failures. e2e logs will show if pods had been been mutated, helping the review phase.
Controller is added in PR https://github.com/redhat-openshift-ecosystem/opct/pull/160
**Which issue(s) this PR fixes**
https://issues.redhat.com/browse/OPCT-352
**Checklist**
=> OPCT-352: collect opct namespace data

artifacts-collector/Containerfile, artifacts-collector/README.md, artifacts-collector/collector.sh, artifacts-collector/global_env.sh, artifacts-collector/manifests/kube-burner-only.yaml
Collect kube-burner profiles to with a simple execution to measure basic performance from clusters in controlled environment (aka know providers/CI) to be used as a baseline while evaluating partner clusters.
Total time increased in the workflow: 9 minutes
Total data collected (additional): ~512K
Those profiles have been used to collect performance report in internal documentation:  [OPCT-276](https://issues.redhat.com/browse/OPCT-276)
=> OPCT-326: collector: gather kube-burner data for basic perf profiles
